name: my-flutter-app
version: '1.0'
summary: An example Flutter snap
description: |
  An example showing how Flutter programs can be packaged as snaps.

base: core22
confinement: strict
grade: stable

apps:
  my-flutter-app:
    command: my_flutter_app
    extensions: [gnome]

parts:
  my-flutter-app:
    source: .
    plugin: flutter
    flutter-target: lib/main.dart

    # This appears to be needed when building in the Snap Store.
    build-packages:
      - curl

# Limit the architectures to build for to prevent unnecessary builds on
# architectures that Flutter doesn't support.
architectures:
  - build-on: [ amd64 ]
  - build-on: [ arm64 ]
