name: my-flutter-app
version: '1.0'
summary: Super Cool App
description: Super Cool App that does everything!
base: core22
confinement: strict
grade: stable

apps:
  my-flutter-app:
    command: my_flutter_app
    extensions: [gnome]

parts:
  my-flutter-app:
    source: .
    plugin: flutter
    flutter-target: lib/main.dart
