name: my-flutter-app
version: '1.0'
summary: An example Flutter snap
description: |
  An example showing how Flutter programs can be packaged as snaps.

base: core22
confinement: strict
grade: stable

architectures:
  - build-on: [ amd64 ]
  - build-on: [ arm64 ]

apps:
  my-flutter-app:
    command: my_flutter_app
    extensions: [gnome]

parts:
  my-flutter-app:
    source: .
    plugin: flutter
    flutter-target: lib/main.dart
